#!/bin/bash

# Check if a filename was provided as an argument
if [ $# -eq 0 ]
then
  echo "Error: No filename provided"
  exit 1
fi

# Store the filename in a variable
filename=$1

# Read the password from the file and store it in a variable
password=$(cat ~/Bash/.password.txt)

# Encrypt the file with the password
openssl enc -aes-256-cbc -salt -in "$filename" -out "$filename.enc" -k "$password"

# Rename the encrypted file to the original filename
mv "$filename.enc" "$filename"

# Change the color of the file to silver
chmod --changes "3777" "$filename"

echo "File encrypted and saved over the original file. Color changed to silver."

